// ASKS ACTION TYPES
export const SET_USER_ASKS = 'SET_USER_ASKS';
export const SET_USER_ASKS_TODO = 'SET_USER_ASKS_TODO';
export const SET_AVAILABLE_ASKS = 'SET_AVAILABLE_ASKS';
export const SET_ASK = 'SET_ASK';
export const REMOVE_ASK = 'REMOVE_ASK';

// USERS ACTION TYPES
export const SET_USER = 'SET_USER';

// CATEGORIES ACTION TYPES
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORY = 'SET_CATEGORY';

// AUTH ACTION TYPES
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SILENT_REFRESH = 'SILENT_REFRESH';
export const RESET_FAILURE = 'RESET_FAILURE';
export const RESET_SUCCESS = 'RESET_SUCCESS';
